config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :categories, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    resource :vote, module: :articles, only: [:create, :destroy]
  end
  devise_for :users, path: 'auth'
  resources :users
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,
            presence: true,
            length: { maximum: 100 }
  validates :text, presence: true
  validates :author, presence: true
  validates :category, presence: true

  has_one_attached :image
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_many :votes, dependent: :destroy

  scope :most_voted, -> { joins(:votes).group('articles.id').order('votes.count DESC').limit(1) }
end

app/controllers/articles/votes_controller.rb
class Articles::VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    @article.votes.where(user_id: current_user.id).first_or_create

    redirect_to @article, notice: 'Thank You For Your Vote! ❤️'
  end

  def destroy
    @article.votes.where(user_id: current_user.id).destroy_all

    redirect_to @article, notice: 'Oh Man! Sorry You Didn\'t love it! 😞'
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :the_author, only: %i[edit update]

  # GET /articles
  def index
    @articles = Article.all
    @most_voted_article = Article.most_voted.first
    @last_written_article = Article.last
    @categories_with_articles = Category.categories_with_articles.limit(4)
  end

  # GET /articles/1
  def show
    @categories_with_articles = Category.categories_with_articles.limit(4)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      flash[:error] = @article.errors.full_messages.to_sentence
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      flash[:error] = @article.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def the_author
    return unless current_user.id != @article.author.id

    redirect_to article_path(@article)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def article_params
    params.require(:article).permit(:title, :text, :author_id, :category_id, :image)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_update(article)
    return unless current_user.id == article.author.id

    content_tag(:div) do
      link_to edit_article_path(article) do
        content_tag(:div, class: 'd-flex') do
          content_tag(:i, class: 'fa fa-pencil mr-2', aria: { hidden: true }) do
          end +
            content_tag(:p) do
              'Edit My Article'
            end
        end
      end
    end +
      content_tag(:div) do
        link_to article_path(article), method: :delete do
          content_tag(:div, class: 'd-flex') do
            content_tag(:i, class: 'fa fa-trash mr-2', aria: { hidden: true }) do
            end +
              content_tag(:p) do
                'Delete My Article'
              end
          end
        end
      end
  end

  def popular_article
    return if @most_voted_article.nil?

    content_tag(:div, class: 'popular') do
      link_to article_path(@most_voted_article), class: 'popular_a' do
        image_tag url_for(@most_voted_article.image), class: 'content_img p_img' if @most_voted_article.image.attached?
      end
    end +
      content_tag(:div, class: 'popular content') do
        link_to article_path(@most_voted_article), class: 'popular_title' do
          content_tag(:p, class: 'title pop_title') do
            @most_voted_article.title
          end +
            content_tag(:p, class: 'text') do
              truncate(@most_voted_article.text, length: 200, omission: '...')
            end
        end
      end
  end

  def last_article
    return if @last_written_article.nil?

    content_tag(:div, class: 'last') do
      link_to article_path(@last_written_article), class: 'last_a' do
        image_tag url_for(@last_written_article.image), class: 'content_img' if @last_written_article.image.attached?
      end
    end +
      content_tag(:div, class: 'last content') do
        link_to article_path(@last_written_article), class: 'last_title' do
          content_tag(:p, class: 'last_title_text') do
            @last_written_article.title
          end
        end
      end
  end
end

app/views/articles/_categories_articles.html.erb
<% unless @categories_with_articles.nil? %>
    
    <% @categories_with_articles.each_with_index do |e, i| %>
      
      <% unless e.first_article.nil? %>
      
        <%= link_to article_path(e.first_article), class: "categ#{i}" do %>
          <%= image_tag url_for(e.first_article.image), class: 'content_img' if e.first_article.image.attached? %>
        <% end %>
        <div class="categ<%= i %>">
          <%= link_to category_path(e), class: "category" do %>
            <%= e.name.upcase %>
          <% end %>
          <%= link_to article_path(e.first_article), class: "title content" do %>
            <%= e.first_article.title %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>

app/views/articles/_form.html.erb
<div class="article_form">
  <%= form_with(model: article, local: true) do |form| %>
    <% if article.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <div class="mr-1 counted_errors"><%= pluralize(article.errors.count, "error") %>:</div>

        <ul class="d-flex flex-column">
          <% article.errors.full_messages.each do |message| %>
            <li class="mr-1"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form_image mt-2">
      <div class="fieldImg d-flex flex-column justify-content-center align-items-center">
        <%= form.label :image, 'Attach A New Image', class: 'attach_text' %>
        <%= form.file_field :image, class: 'attach_field' %>
      </div>
    </div>

    <div class="field categSelectField mb-4">
      <p class="categ_select mt-4">Select Category</p>
      <%= form.label :category%>
      <%= form.collection_select(:category_id, Category.all, :id, :name, {prompt: 'Categories'}) %>
    </div>

    <div class="field title_text_field">
      <%= form.text_field :title, placeholder: 'Title Here', class: 'article_form_style article_title' %>
    </div>

    <div class="field">
      <%= form.text_area :text, placeholder: 'Start Writing Your Amazing Tale...', class: 'article_form_style article_text text_field mt-4' %>
    </div>


    <div class="actions d-flex flex-column">
      <%= form.submit class: 'input_and_a input_style mt-2'  %>
      <%= link_to 'Cancel', articles_path, class: 'input_and_a a_style mt-2' %> 
    </div>
  <% end %>
</div>

app/views/articles/_votes.html.erb
<div class="votes d-flex">
  <% if user_signed_in? && current_user.votes?(article) %>
    
    <div class="downvote">
      <%= link_to article_vote_path(article), method: :delete do %>
        <i class="fa fa-heart mr-2" aria-hidden="true"></i>
      <% end %>
    </div>

  <% else %>
    <div class="upvote">
      <%= link_to article_vote_path(article), method: :post, local: true do %>
        <i class="fa fa-heart-o mr-2" aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>

  <div class="votes_count">
    <%= article.votes.count %>
  </div>
</div>

app/views/articles/edit.html.erb
<section class="article_new middle_section pt-1">
  <div class="article_new_wrapper d-flex flex-column align-items-start mt-4">
    <%= render 'form', article: @article %>
  </div>
</section>

app/views/articles/index.html.erb
<div class="article_index">
    <%= popular_article %>

    <%= last_article%>
  
    <%= render 'articles/categories_articles' %>

</div>

app/views/articles/new.html.erb
<section class="article_new middle_section pt-1 pb-1">
  <div class="article_new_wrapper mt-4 mb-4">
    <%= render 'form', article: @article %>
  </div>
</section>

app/views/articles/show.html.erb
<div class="article_new show middle_section pt-1 pb-1">
  <div class=" article_show mt-4 mb-4">
    <div class="article_show_image">
      <%= image_tag url_for(@article.image), class: 'article_img' if @article.image.attached? %>
    </div>

    <div class="article_show_style">
      <div class="article_title_show mt-4">
        <%= @article.title %>
      </div>

      <div class="below_image mt-4 mb-4">  
        <p class="the_category">
          <strong>Category: </strong>
          <%= @article.category.name %>
        </p>
        <p class="author">
          <strong>Author: </strong>
          <%= @article.author.name %>
        </p>

        <div class="edit_show">
            <%= article_update(@article) %>
        </div>
      </div>

      <div class="article_text">
        <p class="inside_article_text"><%= @article.text %><p>
      </div>

      <div class="votes_show below_image d-flex">
        <p class="message mr-2">Show Your Love By Upvoting This Article!</p>
        <%= render partial: 'votes', locals: { article: @article } %>
      </div>
    </div>
  </div>
</div>