config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :categories, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    resource :vote, module: :articles, only: [:create, :destroy]
  end
  devise_for :users, path: 'auth'
  resources :users
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, -> { order 'created_at DESC' }, dependent: :destroy

  validates :name,
            uniqueness: { case_sensitive: false },
            presence: true,
            length: { in: 3..25 }
  validates :priority,
            presence: true,
            numericality: { only_integer: true }

  scope :ordered_categs, -> { order(priority: :asc) }
  scope :categories_with_articles, -> { ordered_categs.includes(articles: [image_attachment: :blob]) }

  def first_article
    articles.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category, only: %i[edit update destroy]
  before_action :authenticate_user!

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
    @category_with_articles_votes = Category.categories_with_articles.find(params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
    @last_category = Category.last.priority
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_priority
    if @last_category
      content_tag(:em, class: 'mb-2') do
        "(Insert a Priority number greater than #{@last_category})"
      end
    else
      content_tag(:em, class: 'mb-2') do
        '(1 Is The Highest Priority)'
      end
    end
  end
end

app/views/categories/_category_show.html.erb
<% if @category_with_articles_votes.articles.empty? %>
      <h3 class="no_article d-flex flex-column align-items-center">
        Sorry! Category: <%= @category_with_articles_votes.name %> Has No Articles Yet.
        <%= link_to 'Click Here to Write the First Article!', new_article_path %>
      </h3>
      <% else %>
        <div class="articles_in_category">
          <% @category_with_articles_votes.articles.each_with_index do |e, i| %>
            <div class="wrapper_details categ_article_wrapper<%= i %>">
              <div class="categ_article_img">
                <%= image_tag url_for(e.image) if e.image.attached? %>
              </div>
              <div class="categ_article_info">
                <%= link_to category_path(@category_with_articles_votes), class: 'categ_show_name' do %>
                  <%= @category_with_articles_votes.name %>
                <% end %>
                <div class="categ_article_title_text d-flex flex-column">
                  <%= link_to article_path(e) do %>
                    <div><%= e.title %></div>
                    <p><%= truncate(e.text, length: 200, omission: '...(continue reading)') %></p>
                  <% end %>
                </div>
                <div class="categ_articles_votes">
                  <%= render partial: 'articles/votes', locals: { article: e}  %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    <% end %>

app/views/categories/_form.html.erb
<div class="categ_new_edit_form">
  <%= form_with(model: category, local: true) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field d-flex flex-column mt-2">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: 'ie. Technology' %>
    </div>

    <div class="field d-flex flex-column mt-4">
      <%= form.label :priority %>
      <%= category_priority %>
      <%= form.number_field :priority, placeholder: 'Insert A Number' %>
    </div>

    <div class="actions mt-4 mb-2">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<section class="category_edit middle_section">
  <div class="section_header pt-4">
    <h1>Editing Category</h1>
  </div>
  <div class="category_edit_wrapper d-flex flex-column align-items-center mt-4">
    <%= render 'form', category: @category %>
  </div>
</section>

app/views/categories/index.html.erb
<section class="category_index middle_section">
  <div class="section_header pt-4">
    <h1>All Categories</h1>
  </div>

  <div class="category_index_wrapper d-flex flex-wrap mt-4">
    <% @categories.each do |category| %>
      <div class="categories_wrapper d-flex justify-content-center">
        <div class="categ_name mr-4">
          <%= link_to category.name, category %>
        </div>
      </div>
    <% end %>
    <%= link_to new_category_path, class: 'new_category d-flex justify-content-center' do %>
      New Category
      <i class="fa fa-plus ml-2" aria-hidden="true"></i>
    <% end %>
  </div>
</section>

app/views/categories/new.html.erb
<section class="category_new_edit middle_section">
  <div class="section_header pt-4">
    <h1>New Category</h1>
  </div>
  <div class="category_new_edit_wrapper d-flex flex-column align-items-center mt-4">
    <%= render 'form', category: @category %>
  </div>
</section>

app/views/categories/show.html.erb
<section class="category_show middle_section">
  <div class="category_show_grid">
    <%= render 'categories/category_show' %>
  </div>
</section>