config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :categories, except: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    resource :vote, module: :articles, only: [:create, :destroy]
  end
  devise_for :users, path: 'auth'
  resources :users
end

app/views/layouts/_footer.html.erb
<footer class="footer pt-0 pb-0">
  <%= link_to 'EllaMexicana', root_path, class: "footerLogo d-flex align-items-center" %>
  <div class="privacyLi d-flex align-items-center justify-content-start">
    <a href="https://www.behance.net/gallery/14554909/liFEsTlye-Mobile-version" class="privacy pr-2">Privacy Policy</a>
    <a href="https://www.linkedin.com/in/ara-camarillo/" class="madeBy pr-4">Made By Ara CE</a>
    <a href="https://en.wikipedia.org/wiki/Copyright" class="copyright">Copyright 2020. All Rights Reserved.</a>
  </div>
  <div class="footerLi d-flex justify-content-end align-items-center">
    <span>Connect With Us:</span>
    <div class="footer_icons">
      <a href="https://twitter.com/Ara_CE_93" class="twitter">
        <i class="f_icon fa fa-twitter" aria-hidden="true"></i>
      </a>
      <a href="https://www.facebook.com/" class="facebook">
        <i class="f_icon fa fa-facebook" aria-hidden="true"></i>
      </a>
      <a href="https://github.com/aracelicaes" class="github">
        <i class="f_icon fa fa-github" aria-hidden="true"></i>
      </a>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar pb-0 pt-0">      
      <%= link_to 'EllaMexicana', root_path, class: "logo d-flex align-items-center" %>
      
      <div class="links d-flex justify-content-center align-items-center" >
          <%= link_to 'HOME', root_path, class: 'home link'%>
          <%= categories_nav_links %>
          <%= link_to 'MORE', categories_path, class: 'more link' %>
      </div>

      <div class="sessionLi session_li">
       <%= session_links %>
      </div>
    </nav>
    
    <% if notice %><p class="alert alert-info"><%= notice %></p><% end %>
    <% if alert %><p class="alert alert-warning"><%= alert %></p><% end %>
    
    <%= yield %>

    <%= render "layouts/footer" %>
 
  </body>
</html>